#!/bin/sh

# Cambiar idioma del teclado
setxkbmap -layout latam

# Programsa de inicio
exec /usr/libexec/polkit-mate-authentication-agent-1 &
exec ~/.fehbg &
exec plank &
exec cbatticon &
exec nm-applet &
exec volumeicon &

# Fluxbox
exec fluxbox
