#!/bin/sh

opciones="Actualizar\nCancelar"
selec=$(echo $opciones | dmenu -i -p "Elige una opcion" -fn "UbuntuMonoNerdFontMono-12" -nb "#2E3440" -nf "#4C566A" -sb "#5E81AC" -sf "#D8DEE9")
case $selec in
	Actualizar)
		lxterminal -e sudo xbps-install -Suy && sudo xbps-remove -Oo ;;
	Cancelar)
		exit 0 ;;
esac
