#!/bin/sh

opciones="Apagar\nActualizar\nPaginas\nProgramas\nTeclado"
selec=$(echo $opciones | dmenu -i -p "Elige una opcion" -fn "UbuntuMonoNerdFontMono-12" -nb "#2E3440" -nf "#4C566A" -sb "#5E81AC" -sf "#D8DEE9")
case $selec in
	Apagar)
		apagar ;;
	Actualizar)
		actualizar ;;
	Paginas)
		paginas ;;
	Programas)
		programas ;;
	Teclado)
		teclado ;;
	Cancelar)
		exit 0 ;;
esac
